name: build-go-binary

on:
  release:
    types: [created] # 表示在创建新的 Release 时触发

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin] # 需要打包的系统
        goarch: [amd64, arm64] # 需要打包的架构
#        exclude: # 排除某些平台和架构
#          - goarch: arm64
#            goos: windows
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21 # 可以指定编译使用的 Golang 版本

      - name: Set GOOS and GOARCH
        run: |
          echo "GOOS=${{ matrix.goos }}" >> $GITHUB_ENV
          echo "GOARCH=${{ matrix.goarch }}" >> $GITHUB_ENV

      - name: Build
        run: go build -v -o serverandclient ./...

      - name: Test
        run: go test -v ./...

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: serverandclient-${{ matrix.goos }}-${{ matrix.goarch }}
          path: serverandclient
